### PR TITLE
change .gitconfig

### PR DESCRIPTION
**Pull request by vgerman68**

### CODE REVIEW

**Review by vgerman682 — COMMENTED** [review]
check a file

**Comment by vgerman682** [comment]
check a this file

**Review by vgerman68 — COMMENTED** [review]
Check vgerman68

**Review by vgerman682 — APPROVED** [review]
Check2 vgerman682

**Review by vgerman682 — CHANGES_REQUESTED** [review]
Check3 vgerman682

**Review by vgerman682 — APPROVED** [review]

**Review by vgerman682 — APPROVED** [review]

**Review by vgerman682 — COMMENTED** [review]
Check comment vgerman682

**Pull request merged**
